#!/usr/bin/env node

var rest   = require('./rest');
var confd  = require('./index');
var docopt = require('docopt').docopt;

var DEFAULT_PORT = 6868;
var DEFAULT_FROM = '/etc/conf.d';


function startRest(port, from)
{
    port = port || DEFAULT_PORT;
    from = from || DEFAULT_FROM;
    
    console.log('Going to start conf.d service on port "%s", from folder "%s"...', port, from);
    
    rest.run(from, port);
}

function startCli(path, subpath)
{
    var conf = confd.from(path).get(subpath);
    
    console.log(JSON.stringify(conf));
}


var options = 'Either starts the conf.d REST server or the command-line reader \n'
            + '  \n'
            + 'Usage: \n'
            + '  confd cli get <PATH> [<SUBPATH>]\n'
            + '  confd rest [--port <PORT>] [--from <FOLDER>]\n'
            + '  confd -h | --help \n'
            + '  \n'
            + 'Modes: \n'
            + '  cli  Starts the command-line reader\n'
            + '  rest Starts the REST server\n'
            + '  \n'
            + 'Options: \n'
            + '  get <PATH> <SUBPATH> Read the JSON object from <PATH>, eventually scoped to sub-path <SUBPATH> \n'
            + '  --port <PORT>        Instructs the REST server to listen on port <PORT>. Default port is ' + DEFAULT_PORT + '. \n'
            + '  --from <FOLDER>      Instructs the REST server to read data from <FOLDER>. Default folder is ' + DEFAULT_FROM + '. \n'
            + '  -h --help            Shows this help \n';

var cmd = docopt(options);

if (cmd)
{
    if (cmd.rest)
    {
        startRest(cmd['--port'], cmd['--from']);
    }
    else if (cmd.cli)
    {
        startCli(cmd['<PATH>'], cmd['<SUBPATH>']);
    }
}
